jornadayu/yu-open-lib

- .github/workflows/new_release.yml
> Nomear corretamente pipeline de novo release

- .eslintrc
- .github/workflows/new_release.yml
- README.md
- bin/check_unreleased.sh
- bin/set_release_badges.sh
- src/stories/root/Guidelines.stories.mdx
> Corrigir Pipeline manual de novos releases, com badges automaticos de versionamento

- .github/workflows/new_release.yml
- .github/workflows/storybook_build.yml
- .github/workflows/storybook_deploy.yml
> Corrigir sintaxe invalida na pipeline de Novo Release e Deploy

- .github/workflows/new_release.yml
> Corrigir falta de instalação de dependências na Pipeline de release

- .github/workflows/new_release.yml
> Corrigir nome de usuario do git em config de pipeline de release

- .github/workflows/new_release.yml
> Corrigir config de registry do NPM em pipeline de release

- package.json
- src/components/person/PersonAvatar.tsx
- src/index.tsx
- src/stories/person/PersonAvatar.stories.tsx
- yarn.lock
Adicionado componente `PersonAvatar`
---
> Adicionar componente PersonAvatar

- .github/workflows/new_release.yml
> Corrigir path incorreto para script de pre-release

- .github/workflows/new_release.yml
> Corrigir formatação incorreta de Changelog em pipeline de release

- .github/workflows/new_release.yml
> Especificar 'from' e 'to' tags de pipeline de gerador de Changelog (corrige changelog vazio)

- .eslintrc
- package.json
- src/stories/person/PersonAvatar.stories.tsx
- yarn.lock
> Corrigir erros de TypeScript sendo gerados em pipeline de release para o NPM

- .github/workflows/new_release.yml
> Fix missing or incorrect tag inputs in release pipeline

- .storybook/main.js
Path base para assets não estava configurado para o nome do repositório, como necessário para deploys do vite em GitHub pages: https://vitejs.dev/guide/static-deploy.html#github-pages
> Corrigir loading infinito do Storybook

- .github/workflows/storybook_deploy.yml
- src/helpers/index.ts
> [YURI-2611] Alterar condições de build do storybook para executar em mudanças de config do Storybook

- .eslintrc
- .github/workflows/storybook_build.yml
- .github/workflows/storybook_deploy.yml
- src/components/inputs/FileUploadInput.tsx
- src/stories/inputs/FileUploadInput.stories.tsx
> Adicionar componente FileUploadInput

- .github/workflows/configs/changelog-builder.json
- .github/workflows/new_release.yml
- .github/workflows/storybook_deploy.yml
> Corrigir PRs unlabeled nao aparecendo em Changelog de releases

- src/index.tsx
> Corrigir FileUploadInput nao sendo exportada corretamente pela yu-open-lib

- bin/set_release_badges.sh
- src/components/yu/YuFooter.tsx
- src/stories/inputs/FileUploadInput.stories.tsx
- src/stories/person/PersonAvatar.stories.tsx
- src/stories/root/Guidelines.stories.mdx
- src/stories/yu/YuFooter.stories.tsx
> Adicionar prop opcional 'imageSrc' no componente YuFooter

- .github/workflows/storybook_build.yml
- .github/workflows/storybook_deploy.yml
> [YURI-2756] Corrigir problema 'out of memory' ao fazer build/deploy do Storybook

- .eslintrc
- .github/workflows/linting.yml
- .github/workflows/new_release.yml
- src/components/inputs/ImageDragAndDrop.tsx
- src/stories/dialogs/BaseDialog.stories.tsx
- src/stories/dialogs/ConfirmDialog.stories.tsx
- src/stories/dialogs/DialogTitle.stories.tsx
- src/stories/loaders/BackdropLoading.stories.tsx
- src/stories/loaders/LoadingLine.stories.tsx
- tsconfig.json
> Corrigir uso de React Fragments nao-suportados e adicionar eslint rule pra auto-corrigir

- .github/workflows/new_release.yml
> Adicionar configuracao de usuario do git pos-checkout em pipeline de release

- src/components/RichTextViewer.tsx
- src/index.tsx
- src/stories/utils/RichTextViewer.stories.tsx
> [YURI-2820] Viewer de rich text

- src/helpers/text.ts
1. Resolve bug que acontecia ao tentar copiar texto em formato html pela segunda vez na mesma página
---
---
> [YURI-2834] Bug ao tentar copiar textos com formato html mais de uma vez na página corrigido

- .storybook/preview.jsx
- src/index.tsx
- src/stories/dialogs/BaseDialog.stories.tsx
- src/stories/root/AppTheme.stories.mdx
- src/stories/root/Guidelines.stories.mdx
- src/stories/root/Intro.stories.mdx
- src/stories/root/V2Update.stories.mdx
> Adicionar missing export de componente `BaseDialog`

- src/components/graphs/EChartsFunnelGraph.tsx
- src/stories/graphs/EChartsFunnelGraph.stories.tsx
Componente 'EChartsFunnelGraph' agora tem uma Story e novos props:
```ts
type T = {
/**
* Adds customizable legends to chart.
*
* @default false
*/
withLegends?: boolean
/**
* Customization for series options. (ex.: size, positioning, label formatting etc.)
*/
seriesOptions?: Partial<SharedSeriesOptions>
/**
* Customization for graph legends (ex.: positioning, font styling, etc.)
*/
legendOptions?: Partial<EChartOption.Legend>
}
```
---
---
> [YURI-2879] Adicionar props de customização e legendas em componente 'EChartsFunnelGraph'

- .github/configs/changelog-builder.json
- src/components/graphs/EChartsFunnelGraph.tsx
> Atualizar Template de Changelog de releases para ter menos categorias

- .github/workflows/linting.yml
- package.json
- src/helpers/index.ts
- tests/groupBy.test.ts
- vitest.config.ts
- yarn.lock
Helper function `groupBy` tinha a tipagem errada no seu retorno, o que quebrava tipagem de tentativas de remapear dados retornados por ela. Adicionado testes com esse check + testes regulares de retorno da função `groupBy`
---
> Corrigir tipagem de helper 'groupBy' e configurar unit tests

- src/components/chips/StatusChip.tsx
- src/index.tsx
- src/stories/chips/StatusChip.stories.tsx
> Novo componente 'StatusChip'

- src/theme/AppTheme.tsx
> [YURI-2970] Changing MuiCard hard coded background to swtich with theme

- package.json
> Fix npm release being made with no build files (making the package not usable)

- src/components/welcome/Welcome.tsx
- src/index.tsx
- src/stories/welcome/Welcome.stories.tsx
Adiciona componente de Welcome
---
> [YURI-3137] Componente de Welcome

- src/components/meetings/MeetingCard.tsx
- src/stories/meetings/MeetingCard.stories.tsx
> Removido as props desnecessárias em MeetingCard

- src/components/meetings/MeetingCard.tsx
> Fix spacing of `MeetingCard` status chip

- src/components/meetings/MeetingCard.tsx
- src/stories/meetings/MeetingCard.stories.tsx
Esse PR adiciona o props `sx` e modifica a tipagem dos props `startAt` e `endAt`. Adicionado a story With Date.
---
---
> Fix type props of `MeetingCard`

- .github/configs/changelog-builder.json
> [YURI2-204] Change log com link de issues do projeto YURI2

- src/components/welcome/Welcome.tsx
> [YURI2-429] - Nome opcional

- src/components/inputs/FileUploadInput.tsx
---
Adiciona um booleano que se for true, chama a funcao onSubmit automaticamente.
Adiciona uma func que se chamada recebe o File que foi anexado, serve como um hook. 
---
> [YURI2-528] - Criado um props para autoSave e uma func que e chamada ao anexar algum arquivo

- .github/workflows/new_release.yml
Corrige: https://github.com/jornadayu/yu-open-lib/runs/8156280820?check_suite_focus=true
---
> Configurar identidade do git em GitHub Action de novos releases

- src/components/NavBar/BaseAppBar.tsx
- src/components/NavBar/NavBarStyles.ts
- src/components/NavBar/YuMobileNavBar.tsx
Adiciona um boolean da variável `withMobileIcons` q caso saja `true` e o `drawer` seja `false` é adicionado os ícones ao lado
> [YURI2-842] - Ícones fora do menu hamburguer no header

- src/components/notifications/NotificationMenu.tsx
- src/index.tsx
- src/stories/notifications/NotificationMenu.stories.tsx
---
Cria o componente de notificação, contendo um icone e um menu de notificações quando é clicado nesse link.
---
> [YURI2-1261] - Criado o componente de notificacoes

- src/components/NavBar/BaseAppBar.tsx
- src/components/NavBar/YuMobileNavBar.tsx
- src/components/notifications/NotificationMenu.tsx
- src/stories/navbar/YuAppBar.stories.tsx
---
Faz com que o YuAppBar mobile aceite um novo icone/item na barra superior, renderizando esse item ao lado esquerdo da logo.
---
> [YURI2-1262] - Header mobile aceita um item novo na barra.

- package.json
> Fix story book build

- src/components/notifications/NotificationItem.tsx
- src/index.tsx
> Exportando default o notificationItem

- src/assets/icons/yu/negative/SalmaoIcon.tsx
- src/assets/icons/yu/positive/SalmaoIcon.tsx
- src/components/cookies/CookiesWarning.tsx
- src/components/notifications/NotificationItem.tsx
- src/components/notifications/NotificationMenu.tsx
- src/index.tsx
- src/stories/cookies/CookiesWarning.stories.tsx
> [YURI2-1125] - Notificação de Cookies

- .eslintrc
- package.json
- src/components/chips/StatusChip.tsx
- src/components/cookies/CookiesWarning.tsx
- src/components/graphs/AverageStepDurationGraph.tsx
- src/components/graphs/EChartsFunnelGraph.tsx
- src/components/graphs/bar/DiversityBarGraph.tsx
- src/components/table/DataTableCell.tsx
- src/components/table/DataTablePagination.tsx
- src/components/table/DataTableRow.tsx
- src/components/welcome/Welcome.tsx
- src/stories/graphs/YuWordCloud.stories.tsx
- src/stories/inputs/VCardQRCode.stories.tsx
- src/stories/welcome/Welcome.stories.tsx
- yarn.lock
> Fix hooks being called conditionally or with wrong dependencies
